# frozen_string_literal: true

require "exception_notification/rails"

ExceptionNotification.configure do |config|
  # Ignore additional exception types.
  # ActiveRecord::RecordNotFound, Mongoid::Errors::DocumentNotFound, AbstractController::ActionNotFound and ActionController::RoutingError are already added.
  config.ignored_exceptions += %w[Blacklight::Exceptions::RecordNotFound]

  # Adds a condition to decide when an exception must be ignored or not.
  # The ignore_if method can be invoked multiple times to add extra conditions.
  config.ignore_if do |exception, options|
    !Rails.env.production?
  end

  # Ignore exceptions generated by crawlers
  config.ignore_crawlers %w[Googlebot bingbot meta-externalagent]

  # Group repeated failures so noisy production errors do not spam email.
  config.error_grouping = true
  config.error_grouping_period = 1.day

  # Notifiers =================================================================

  # Email notifier sends notifications by email.
  config.add_notifier :email, {
    email_prefix: "[GeoDiscovery ERROR]",
    sender_address: %("GeoDiscovery" <notifier@#{`hostname`.strip}>),
    exception_recipients: %w[gisdata@uwm.edu],
    verbose_subject: false,
    normalize_subject: true,
    sections: %w[request backtrace],
    background_sections: %w[data backtrace]
  }

  # Campfire notifier sends notifications to your Campfire room. Requires 'tinder' gem.
  # config.add_notifier :campfire, {
  #   subdomain: 'my_subdomain',
  #   token: 'my_token',
  #   room_name: 'my_room'
  # }

  # HipChat notifier sends notifications to your HipChat room. Requires 'hipchat' gem.
  # config.add_notifier :hipchat, {
  #   api_token: 'my_token',
  #   room_name: 'my_room'
  # }

  # Webhook notifier sends notifications over HTTP protocol. Requires 'httparty' gem.
  # config.add_notifier :webhook, {
  #   url: 'http://example.com:5555/hubot/path',
  #   http_method: :post
  # }

end
